export type PermalinkedSettings = {
    seed: number
    difficulty: number
    goal: number
    logic: number
    statues: string
    statue_req: number
    enemizer: number
    start_location: number
    firebird: boolean
    ohko: boolean
    red_jewel_madness: boolean
    allow_glitches: boolean
    boss_shuffle: boolean
    open_mode: boolean
    sprite: string
    overworld_shuffle: boolean
    entrance_shuffle?: number
    town_shuffle?: boolean
    dungeon_shuffle: boolean
    coupled_exits?: boolean
    z3: boolean
    fluteless?: boolean
    flute?: number
    orb_rando?: boolean
    darkrooms?: number
    infinite_inventory?: boolean
    ds_warp?: boolean
    return_spoiler?: boolean
    race_mode?: boolean
}
