export default interface GenerateSeedRequest {
    seed: number
    difficulty: number
    goal: number
    logic: number
    statues: string
    statueReq: number
    enemizer: number
    startLocation: number
    firebird: boolean
    ohko: boolean
    redJewelMadness: boolean
    allowGlitches: boolean
    bossShuffle: boolean
    openMode: boolean
    z3Mode: boolean
    overworldShuffle: boolean
    generateRaceRom: boolean
    flute: number
    dungeonShuffle: boolean
    townShuffle: boolean
    coupledExits: boolean
    hideSettings: boolean
    orbRando: boolean
    darkRooms: number
    cursedRooms: boolean
    infiniteInventory: boolean
    dsWarp: boolean
    returnSpoiler: boolean
}
