export enum DarkSpace {
    Random,
    SouthCape,
    EdwardsPrison,
    UndergroundTunnel,
    ItoryVillage,
    IncaRuins1,
    IncaRuins2,
    IncaRuinsFinal,
    Freejia,
    DiamondMineAppearing,
    DiamondMineAtWall,
    DiamondMineBehindWall,
    SkyGardenFoyer,
    SkyGardenSE,
    SkyGardenSW,
    SkyGardenNW,
    SeasidePalace,
    MuOpen,
    MuSlidder,
    AngelVillage,
    Watermia,
    GreatWallArcher,
    GreatWallSpin,
    GreatWallAppearing,
    Euro,
    Kress1,
    Kress2,
    KressAuraBarrier,
    AnkorWatGarden,
    AnkorWatEarthQuaker,
    AnkorWatDropDown,
    Dao,
    PyramidTop,
    PyramidBottom,
    BabelTop,
    BabelBottom
}

export const DarkSpaceNames = {
    [DarkSpace.Random]: "Random",
    [DarkSpace.SouthCape]: "South Cape",
    [DarkSpace.EdwardsPrison]: "Edward's Prison",
    [DarkSpace.UndergroundTunnel]: "Underground Tunnel",
    [DarkSpace.ItoryVillage]: "Itory Village",
    [DarkSpace.IncaRuins1]: "Inca Ruins 1",
    [DarkSpace.IncaRuins2]: "Inca Ruins 2",
    [DarkSpace.IncaRuinsFinal]: "Inca Ruins Final",
    [DarkSpace.Freejia]: "Freejia",
    [DarkSpace.DiamondMineAppearing]: "Diamond Mine Appearing",
    [DarkSpace.DiamondMineAtWall]: "Diamond Mine At Wall",
    [DarkSpace.DiamondMineBehindWall]: "Diamond Mine Behind Wall",
    [DarkSpace.SkyGardenFoyer]: "Sky Garden Foyer",
    [DarkSpace.SkyGardenSE]: "Sky Garden SE",
    [DarkSpace.SkyGardenSW]: "Sky Garden SW",
    [DarkSpace.SkyGardenNW]: "Sky Garden NW",
    [DarkSpace.SeasidePalace]: "Seaside Palace",
    [DarkSpace.MuOpen]: "Mu Open",
    [DarkSpace.MuSlidder]: "Mu Slidder",
    [DarkSpace.AngelVillage]: "Angel Village",
    [DarkSpace.Watermia]: "Watermia",
    [DarkSpace.GreatWallArcher]: "Great Wall Archer",
    [DarkSpace.GreatWallSpin]: "Great Wall Spin",
    [DarkSpace.GreatWallAppearing]: "Great Wall Appearing",
    [DarkSpace.Euro]: "Euro",
    [DarkSpace.Kress1]: "Kress 1",
    [DarkSpace.Kress2]: "Kress 2",
    [DarkSpace.KressAuraBarrier]: "Kress Aura Barrier",
    [DarkSpace.AnkorWatGarden]: "Ankor Wat Garden",
    [DarkSpace.AnkorWatEarthQuaker]: "Ankor Wat EarthQuaker",
    [DarkSpace.AnkorWatDropDown]: "Ankor Wat Drop Down",
    [DarkSpace.Dao]: "Dao",
    [DarkSpace.PyramidTop]: "Pyramid Top",
    [DarkSpace.PyramidBottom]: "Pyramid Bottom",
    [DarkSpace.BabelTop]: "Babel Top",
    [DarkSpace.BabelBottom]: "Babel Bottom"
}